version: "3.9"

services:
  web:
    build: .
    command: python legalproject/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code/legalproject
    ports:
      - 8000:8000
    environment:
      - POSTGRES_NAME=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_NAME=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    env_file:
      - .env
volumes:
  postgres_data:
