name: Projeto Integrador II
on: [pull_request, push]

jobs:
  test:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install-Requirements
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Tests
      run: |
        pytest -s

    # TODO #001 - Configurar o CI/CD (GitHub Actions) lendo as var. do .env
    #- name: Build
    #  run: |
    #    docker-compose build --no-cache

    #- name: Tests
    #  run: |
    #    docker-compose run web pytest -s
